spring:
  application:
    name: dubbo-provider
  main:
    allow-bean-definition-overriding: true # 允许重名bean覆盖，设置后不会与Spring Boot冲突
dubbo:
  protocol:
    status: server
    name: dubbo
    port: 12345
  registry:
    address: zookeeper://127.0.0.1:2181 #注册中心地址
    file: dubbo-registry/dubbo-registry.properties  #注册中心的本地缓存配置
demo:
  service:
    version: 1.0.0